#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'
require 'mutt/ldap/query'

worker = Mutt::Ldap::Query::Worker.new(ARGV)

options = {
  gen_config: false,
  edit_config: false,
}

OptionParser.new do |opts|
  opts.on('--gen-config', 'Install a sample configuration file') do
    options[:gen_config] = true
    options[:edit_config] = true
  end

  opts.on('--edit-config', 'Edit the current configuration file') do
    options[:edit_config] = true
  end
end.parse!

worker.gen_config if options[:gen_config]
worker.edit_config if options[:edit_config]
exit 0 if options[:gen_config] || options[:edit_config]

unless worker.configured?
  warn "#{worker.config_path} does not exist.  Try `#{$PROGRAM_NAME} --gen-config`."
  exit 1
end

result = worker.search

puts "LDAP query returned #{result.size} entr#{result.size == 1 ? 'y' : 'ies'}."
puts result.join("\n")
